# Stubs for django.utils.translation.template (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

dot_re: Any

def blankout(src, char): ...

context_re: Any
inline_re: Any
block_re: Any
endblock_re: Any
plural_re: Any
constant_re: Any

def templatize(src, origin: Optional[Any] = ..., charset: str = ...): ...
