# Stubs for django.utils._os (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from os.path import abspath
from typing import Any

fs_encoding: Any
abspathu = abspath

def upath(path): ...
def npath(path): ...
def safe_join(base, *paths): ...
def symlinks_supported(): ...
