# Stubs for django.utils.dateparse (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

date_re: Any
time_re: Any
datetime_re: Any
standard_duration_re: Any
iso8601_duration_re: Any

def parse_date(value): ...
def parse_time(value): ...
def parse_datetime(value): ...
def parse_duration(value): ...
