# Stubs for django.utils.numberformat (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def format(number, decimal_sep, decimal_pos: Optional[Any] = ..., grouping: int = ..., thousand_sep: str = ..., force_grouping: bool = ...): ...
