# Stubs for django.utils.termcolors (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

color_names: Any
foreground: Any
background: Any
RESET: str
opt_dict: Any

def colorize(text: str = ..., opts: Any = ..., **kwargs): ...
def make_style(opts: Any = ..., **kwargs): ...

NOCOLOR_PALETTE: str
DARK_PALETTE: str
LIGHT_PALETTE: str
PALETTES: Any
DEFAULT_PALETTE = DARK_PALETTE

def parse_color_setting(config_string): ...
