# Stubs for django.utils.xmlutils (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from xml.sax.saxutils import XMLGenerator

class UnserializableContentError(ValueError): ...

class SimplerXMLGenerator(XMLGenerator):
    def addQuickElement(self, name, contents: Optional[Any] = ..., attrs: Optional[Any] = ...): ...
    def characters(self, content): ...
